branch-defaults:
  deploy_heroku:
    environment: fc-rails-dev
environment-defaults:
  fc-rails-dev:
    branch: null
    repository: null
global:
  application_name: trainings-infra
  default_ec2_keyname: fc-rails-training
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Puma with Ruby 2.5
    running on 64bit Amazon Linux/2.8.3
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
