development:
    mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
    mailer_username: <%= ENV["MAILER_USERNAME"] %>
    mailer_password: <%= ENV["MAILER_PASSWORD"] %>
    mailer_port: <%= ENV["MAILER_PORT"] %>
    mailer_address: <%= ENV["MAILER_ADDRESS"] %>
